default_platform(:mac)

APP_STORE_CONNECT_BUNDLE_IDENTIFIER = ENV["APP_STORE_CONNECT_MACOS_BUNDLE_IDENTIFIER"] || "com.nkust.ap.flutter"

platform :mac do
  lane :release do |options|
    key_id = options[:key_id]
    issuer_id = options[:issuer_id]

    changelog_file = "./zh-TW.txt"
    changelog = File.exist?(changelog_file) ? File.read(changelog_file) : "Bug fixes and improvements."

    api_key = app_store_connect_api_key(
        key_id: key_id,
        issuer_id: issuer_id,
        key_filepath: "./AuthKey.p8",
        duration: 1200,
        in_house: false
    )

    pkg_path = Dir["../build/macos/Build/Products/Release/*.app"].first
    raise "No .app found in build/macos/Build/Products/Release/" if pkg_path.nil?

    upload_to_testflight(
      app_identifier: APP_STORE_CONNECT_BUNDLE_IDENTIFIER,
      api_key: api_key,
      pkg: pkg_path,
      skip_submission: true,
      notify_external_testers: true,
      changelog: changelog,
    )
  end
end
