default_platform(:ios)

APP_STORE_CONNECT_BUNDLE_IDENTIFIER = ENV["APP_STORE_CONNECT_BUNDLE_IDENTIFIER"]

platform :ios do
  lane :release do |options|
    key_id = options[:key_id]
    issuer_id = options[:issuer_id]

    changelog_file = "./zh-TW.txt"
    changelog = File.exist?(changelog_file) ? File.read(changelog_file) : "Bug fixes and improvements."

    api_key = app_store_connect_api_key(
        key_id: key_id,
        issuer_id: issuer_id,
        key_filepath: "./AuthKey.p8",
        duration: 1200,
        in_house: false
    )

    ipa_path = Dir["../build/ios/ipa/*.ipa"].first
    raise "No IPA file found in build/ios/ipa/" if ipa_path.nil?

    localized_info = {
      "default": {
        whats_new: changelog,
      },
    }

    en_file = "./en-US.txt"
    if File.exist?(en_file)
      localized_info["en-US"] = { whats_new: File.read(en_file) }
    end

    upload_to_testflight(
      app_identifier: "#{APP_STORE_CONNECT_BUNDLE_IDENTIFIER}",
      api_key: api_key,
      ipa: ipa_path,
      skip_submission: true,
      notify_external_testers: true,
      changelog: changelog,
      localized_build_info: localized_info,
    )
  end
end
