default_platform(:ios)

APP_STORE_CONNECT_BUNDLE_IDENTIFIER = ENV["APP_STORE_CONNECT_BUNDLE_IDENTIFIER"]

sh("chmod", "a+x", "../../.github/scripts/generate_ios_changelog.sh")

sh("../../.github/scripts/generate_ios_changelog.sh", flutter_version()["version_code"])

platform :ios do
  lane :release do |options|
    key_id = options[:key_id]
    issuer_id = options[:issuer_id]
    changelog = File.read("./zh-TW.txt")
    api_key = app_store_connect_api_key(
        key_id: key_id,
        issuer_id: issuer_id,
        key_filepath: "./AuthKey.p8",
        duration: 1200, # optional (maximum 1200)
        in_house: false # optional but may be required if using match/sigh
    )
    upload_to_testflight(
      app_identifier: "#{APP_STORE_CONNECT_BUNDLE_IDENTIFIER}",
      api_key: api_key,
      ipa: "../build/ios/ipa/nsysuap.ipa",
      skip_submission: true,
      notify_external_testers: true,
      changelog: changelog,
      localized_build_info: {
          "default": {
            whats_new: File.read("./zh-TW.txt"),
          },
          "en-US": {
            whats_new: File.read("./en-US.txt"),
          }
      }
    )
  end
end