default_platform(:ios)

APP_STORE_CONNECT_APPLE_ID = ENV["APP_STORE_CONNECT_APPLE_ID"]
APP_STORE_CONNECT_BUNDLE_IDENTIFIER = ENV["APP_STORE_CONNECT_BUNDLE_IDENTIFIER"]
PROVISIONING_PROFILE_SPECIFIER = ENV["PROVISIONING_PROFILE_SPECIFIER"]
TEMP_KEYCHAIN_USER = ENV["TEMP_KEYCHAIN_USER"]
TEMP_KEYCHAIN_PASSWORD = ENV["TEMP_KEYCHAIN_PASSWORD"]

def delete_temp_keychain(name)
  delete_keychain(
    name: name
  ) if File.exist? File.expand_path("~/Library/Keychains/#{name}-db")
end

def create_temp_keychain(name, password)
  create_keychain(
    name: name,
    password: password,
    unlock: false,
    timeout: false
  )
end

def ensure_temp_keychain(name, password)
  delete_temp_keychain(name)
  create_temp_keychain(name, password)
end


sh("chmod", "a+x", "../../.github/scripts/generate_ios_changelog.sh")

sh("../../.github/scripts/generate_ios_changelog.sh", flutter_version()["version_code"])

platform :ios do
  lane :release do
    keychain_name = TEMP_KEYCHAIN_USER
    keychain_password = TEMP_KEYCHAIN_PASSWORD
    ensure_temp_keychain(keychain_name, keychain_password)

    match(
      type: 'appstore',
      app_identifier: ["#{APP_STORE_CONNECT_BUNDLE_IDENTIFIER}", "#{APP_STORE_CONNECT_BUNDLE_IDENTIFIER}.CourseAppWidget"],
      git_basic_authorization: Base64.strict_encode64(ENV["GIT_AUTHORIZATION"]),
      readonly: true,
      keychain_name: keychain_name,
      keychain_password: keychain_password
    )

    gym(
      configuration: "Release",
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
            APP_STORE_CONNECT_APPLE_ID => PROVISIONING_PROFILE_SPECIFIER
        }
      }
    )

    pilot(
      apple_id: "#{APP_STORE_CONNECT_APPLE_ID}",
      app_identifier: "#{APP_STORE_CONNECT_BUNDLE_IDENTIFIER}",
      skip_waiting_for_build_processing: true,
      skip_submission: true,
      distribute_external: false,
      notify_external_testers: true,
      ipa: "./Runner.ipa",
      localized_build_info: {
          "default": {
            whats_new: File.read("./zh-TW.txt"),
          },
          "en-US": {
            whats_new: File.read("./en-US.txt"),
          }
        }
    )

    delete_temp_keychain(keychain_name)
  end
end