// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpHUWczANDziA-Gzxoh_ybGnEZq9JmKL4',
    appId: '1:141403473068:web:2804dce650446efef34b09',
    messagingSenderId: '141403473068',
    projectId: 'nkust-ap-flutter',
    authDomain: 'nkust-ap-flutter.firebaseapp.com',
    databaseURL: 'https://nkust-ap-flutter.firebaseio.com',
    storageBucket: 'nkust-ap-flutter.appspot.com',
    measurementId: 'G-TSD51EKRLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBIKkKaOfI4nDmj_SN738yB_IUVEOZiAo',
    appId: '1:141403473068:android:05ebdd62590fb72e',
    messagingSenderId: '141403473068',
    projectId: 'nkust-ap-flutter',
    databaseURL: 'https://nkust-ap-flutter.firebaseio.com',
    storageBucket: 'nkust-ap-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCAbWwVkQZEcy-x3_NhGqXxjcTdtB6Kj4',
    appId: '1:141403473068:ios:65aa63de8e144164',
    messagingSenderId: '141403473068',
    projectId: 'nkust-ap-flutter',
    databaseURL: 'https://nkust-ap-flutter.firebaseio.com',
    storageBucket: 'nkust-ap-flutter.appspot.com',
    androidClientId: '141403473068-46ao3s54s6jio6nndl70sq26k0bpki6g.apps.googleusercontent.com',
    iosClientId: '141403473068-b9ugkddmql2nefsuggoc9unte0qm23eb.apps.googleusercontent.com',
    iosBundleId: 'com.nkust.ap.flutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCAbWwVkQZEcy-x3_NhGqXxjcTdtB6Kj4',
    appId: '1:141403473068:ios:568f2386591e74bbf34b09',
    messagingSenderId: '141403473068',
    projectId: 'nkust-ap-flutter',
    databaseURL: 'https://nkust-ap-flutter.firebaseio.com',
    storageBucket: 'nkust-ap-flutter.appspot.com',
    androidClientId: '141403473068-46ao3s54s6jio6nndl70sq26k0bpki6g.apps.googleusercontent.com',
    iosClientId: '141403473068-r9a6m4f8lmg31e5v08v1kfnnn8cin8iv.apps.googleusercontent.com',
    iosBundleId: 'com.nkust.nkustApFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpHUWczANDziA-Gzxoh_ybGnEZq9JmKL4',
    appId: '1:141403473068:web:d71d06f2e8822143f34b09',
    messagingSenderId: '141403473068',
    projectId: 'nkust-ap-flutter',
    authDomain: 'nkust-ap-flutter.firebaseapp.com',
    databaseURL: 'https://nkust-ap-flutter.firebaseio.com',
    storageBucket: 'nkust-ap-flutter.appspot.com',
    measurementId: 'G-NFNWK0YG2P',
  );
}
