default_platform(:android)

platform :android do
  lane :beta do
    desc "Deploy to beta track"
    upload_to_play_store(
      track: 'beta',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
      version_code: flutter_version()["version_code"],
    )
  end

  lane :playstore do
    desc "Deploy to production track"
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      release_status: "draft",
      version_code: flutter_version()["version_code"],
    )
  end
end
